# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionInfo',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=64)),
                ('hostIP', models.CharField(max_length=32)),
                ('regionName', models.CharField(max_length=32)),
                ('licenseID', models.CharField(max_length=32)),
                ('license', models.CharField(max_length=64)),
                ('hostID', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('userphone', models.CharField(max_length=32)),
                ('unitcode', models.CharField(max_length=32)),
                ('unitname', models.CharField(max_length=64)),
            ],
        ),
    ]
